services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: fkvdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fkvdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-app:
    build: ./fkv-service
    ports:
      - "8000:8000"
    volumes:
      - ./fkv-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DBHOST=postgres
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASS=12345678
      - DBNAME=fkvdb
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  node-app:
    build:
      context: ./fkv-client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./fkv-client:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
