"""add flats

Revision ID: 26400e0aaafe
Revises: 
Create Date: 2025-03-18 18:22:06.556708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26400e0aaafe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('all_square', sa.Integer(), nullable=False),
    sa.Column('life_square', sa.Integer(), nullable=False),
    sa.Column('kit_square', sa.Integer(), nullable=False),
    sa.Column('center_dist', sa.Integer(), nullable=False),
    sa.Column('metro_dist', sa.Integer(), nullable=False),
    sa.Column('amount_rooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('walk', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    # ### end Alembic commands ###
