"""create types

Revision ID: 8b70c36fe624
Revises: f6f61dc41dc1
Create Date: 2025-04-18 05:59:28.778263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b70c36fe624'
down_revision: Union[str, None] = 'f6f61dc41dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('all_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('life_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kit_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('center_dist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metro_dist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_rooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('walk', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='flats_pkey')
    )
    # ### end Alembic commands ###
