"""create users

Revision ID: f6f61dc41dc1
Revises: 
Create Date: 2025-04-17 16:59:09.024766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f61dc41dc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('second_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    op.create_table('flats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('all_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('life_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kit_square', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('center_dist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metro_dist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_rooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('walk', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='flats_pkey')
    )
    # ### end Alembic commands ###
